<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GVPIIJD" failures="1" tests="10" name="Run on Chrome" time="98.594" errors="0" timestamp="2025-05-18T19:00:46 IST">
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Scroll_using_javascript" time="8.616"/>
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Scroll_using_javascript_bottom_page" time="4.399"/>
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Scroll_using_javascript_specific_pixels" time="3.978"/>
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="DragAndDrop" time="7.118"/>
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="DragAndDrop" time="27.917"/>
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Verify" time="0.017">
    <skipped/>
  </testcase> <!-- Verify -->
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Verify" time="0.003">
    <skipped/>
  </testcase> <!-- Verify -->
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Verify" time="0.001">
    <skipped/>
  </testcase> <!-- Verify -->
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="Verify" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	First failure,
	Second failure">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
First failure,
Second failure
at SeleniumTopic.Selenium_Suite_parallel.Verify(Selenium_Suite_parallel.java:220)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Verify -->
  <testcase classname="SeleniumTopic.Selenium_Suite_parallel" name="rightClick" time="11.256"/>
</testsuite> <!-- Run on Chrome -->
